# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Package EnvCalc Backend

on:
  push:
    branches: [ backend/main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./src/Backend/
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2  
        with:
          java-version: '16'
          distribution: 'adopt'
      - run: mvn -Dspring.profiles.active=build --batch-mode --update-snapshots verify 
      - name: Login
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build image 
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/nexusmeister/envcalc/envcalc-backend:latest
      - name: Push image
        run: docker push docker.pkg.github.com/nexusmeister/envcalc/envcalc-backend:latest
     
