# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Package EnvCalc Backend

on:
  push:
    branches: [ backend/main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./src/Backend/
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2  
        with:
          java-version: '16'
          distribution: 'adopt'
      - run: mvn -Dspring.profiles.active=build --batch-mode --update-snapshots verify 
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          file: src/Backend/Dockerfile
          context: ./src/Backend
          push: true
          tags: docker.pkg.github.com/nexusmeister/envcalc/envcalc-backend:latest
