name: Build Frontend

on:
  workflow_dispatch :
  pull_request:
    branches: [ frontend/main ]

jobs:
  'Build & Test':
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src/Frontend/EnvCalc.Frontend/EnvCalc.Frontend/
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
