name: Publish EnvCalc Frontend 

on:
  workflow_dispatch :

jobs:
  TestAndPublish:

    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./src/Frontend/EnvCalc.Frontend/EnvCalc.Frontend/
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c Release --no-restore
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::v$(date +'%Y.%m.%d.%H%M')"
    - name: Datenstruktur
      run: ls -R
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
         tag_name: ${{ steps.date.outputs.date }}
         release_name: Release EnvCalc ${{ steps.date.outputs.date }}
         draft: false
         prerelease: false
    - name: Archive site content
      uses: thedoctor0/zip-release@master
      with:
        filename: envcalc_frontend.zip
        path: D:\a\EnvCalc\EnvCalc\src\Frontend\EnvCalc.Frontend\EnvCalc.Frontend\bin\Release\net5.0-windows\
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./envcalc_frontend.zip
        asset_name: envcalc-${{ steps.date.outputs.date }}.zip
        asset_content_type: application/zip
      
      
      
      
    
